baseURL = 'http://duomomentum.com/'
languageCode = 'en-us'
title = 'Duo Momentum'

[build]
  useResourceCacheWhen = 'fallback'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Project Documentation'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
  [languages.fi]
    contentDir = 'content'
    disabled = false
    languageCode = 'fi-FI'
    languageDirection = 'ltr'
    languageName = 'Suomi'
    title = 'Projekt Dokumentation'
    weight = 2
    [languages.fi.params]
      subtitle = 'subtitle suomeksi'

    [[languages.en.menu.main]]
      name        = "Home"
      url         = "/"
      weight     = 1
    [[languages.en.menu.main]]
      name        = "About us"
      url         = "/about/"
      weight     = 2
    [[languages.en.menu.main]]
      name        = "Performances"
      url         = "/performance/"
      weight     = 3

    [[languages.fi.menu.main]]
      name        = "Koti"
      url         = "/"
      weight     = 1
    [[languages.fi.menu.main]]
      name        = "Meistä"
      url         = "/fi/about/"
      weight     = 2
    [[languages.fi.menu.main]]

      name        = "Esitykset"
      url         = "/fi/performance/"
      weight     = 3


[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3